=== mbgt/testcase/src/test/resources/xsd/testCase.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
        xmlns:tc="testcase"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://java.sun.com/xml/ns/jaxb bindingschema_2_0.xsd"
        targetNamespace="testcase"
        elementFormDefault="qualified"
        attributeFormDefault="unqualified" jxb:version="2.1">
    
    <annotation>
        <appinfo>
            <jxb:schemaBindings>
                <jxb:package name="ch.mab.tc.jaxb"/>
            </jxb:schemaBindings>
        </appinfo>
    </annotation>

    <element name="testcase" type="tc:testcaseType"/>

    <element name="inkassoFall" type="tc:inkassoFallType"/>

    <complexType name="inkassoFallType">
        <sequence>
            <element name="faktura" minOccurs="0" type="tc:fakturaType"/>
        </sequence>
        <attribute name="id" type="ID"/>
        <attribute name="zpvnr" type="int" />
        <attribute name="forderungsart" type="tc:forderungsartType"/>
        <attribute name="forderungjahr" type="tc:jahrType"/>
    </complexType>

    <complexType name="fakturaType">
        <sequence>
            <element name="position" minOccurs="0" maxOccurs="9" type="tc:positionType"/>
        </sequence>
        <attribute name="valuta" type="date" use="required"/>
        <attribute name="id" type="ID"/>
    </complexType>


    <complexType name="positionType">
        <all>
            <element name="kategorie" type="tc:kategorieType"/>
            <element name="institution" type="tc:institutionType"/>
            <element name="betrag" type="decimal"/>
        </all>
    </complexType>

    <complexType name="kategorieType">
        <attribute name="type" type="string"/>
        <attribute name="subtype" type="string"/>
    </complexType>

    <complexType name="institutionType">
        <attribute name="art" type="string"/>
        <attribute name="nummer" type="int"/>
    </complexType>

    <complexType name="testcaseType">
        <sequence>
            <element name="inkassoFall" minOccurs="0" maxOccurs="unbounded" type="tc:inkassoFallType"/>
            <element name="when" type="tc:whenType"/>
            <element name="then" type="tc:thenType"/>
        </sequence>
    </complexType>

    <complexType name="whenType">
        <all>
            <element name="esr" type="tc:esrTyp"/>
        </all>
    </complexType>

    <complexType name="thenType"></complexType>
    
    <complexType name="esrTyp">
        <attribute name="art" type="tc:esrArtType"/>
        <attribute name="faktura" type="IDREF"/>
    </complexType>

    <simpleType name="forderungsartType" >
        <restriction base="string">
            <enumeration value="BST_NP"/>
            <enumeration value="BST_JP"/>
            <enumeration value="DBS_NP"/>
            <enumeration value="DBS_JP"/>
        </restriction>
    </simpleType>
     
    <simpleType name="esrArtType">
        <restriction base="int">
            <enumeration value="1"/>
            <enumeration value="2"/>
            <enumeration value="3"/>
            <enumeration value="4"/>
            <enumeration value="5"/>
        </restriction>
    </simpleType>    
    
    <simpleType name="jahrType">
        <restriction base="int">
            <minInclusive value="2000"/>
            <maxInclusive value="2100"/>
        </restriction>
    </simpleType>
</schema>

=== mbgt/testcase/src/test/resources/testcase/esrZahlung.xml
<?xml version="1.0" encoding="UTF-8"?>

<testcase xmlns="testcase"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation='testcase ../xsd/testcase.xsd'>
    <inkassoFall id="ik1" forderungsjahr="2015" forderungsart="BST_NP" zpvnr="1">
        <faktura id="fk11" valuta="2015-01-01" belegart="schlussabrechnung">
            <position>
                <kategorie type="einkommenssteuer"/>
                <institution art="kanton"/>
                <betrag>100</betrag>
            </position>
            <position>
                <kategorie type="vermoegenssteuer"/>
                <institution art="kanton" nummer="1"/>
                <betrag>200</betrag>
            </position>
        </faktura>
    </inkassoFall>
    <inkassoFall id="ik2" forderungsjahr="2016" forderungsart="BST_NP" zpvnr="1">
        <faktura id="fk21" valuta="2016-01-01" belegart="provisorische_abrechnung">
            <position>
                <kategorie type="einkommenssteuer"/>
                <institution art="gemeinde" nummer="1234"/>
                <betrag>300</betrag>
            </position>
        </faktura>
        <faktura  id="fk22" valuta="2017-12-01" belegart="schlussabrechnung">
            <position>
                <kategorie type="einkommenssteuer"/>
                <institution art="gemeinde" nummer="1234"/>
                <betrag>1000</betrag>
            </position>
        </faktura>
    </inkassoFall>
    <when>
        <esr art="1" faktura="fk11" betrag="900"/>
    </when>
    <then>
        <kontoauszug valuta="2017-01-01" belegart="zahlung" konto="V_BST">
            <position>
                <kategorie type="einkommenssteuer"/>
                <institution art="kanton"/>
                <betrag>800</betrag>
            </position>
        </kontoauszug>
    </then>
</testcase>

=== mbgt/testcase/src/test/resources/testcase/esrzahlung.xml
<?xml version="1.0" encoding="UTF-8"?>

<testcase xmlns="testcase"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation='testcase.xsd ../xsd/testcase.xsd'>
    <inkassoFall id="ik1" forderungjahr="2015" forderungsart="BST_NP" zpvnr="1">
        <faktura id="fk11" valuta="2015-01-01">
            <position>
                <kategorie type="" subtype=""/>
                <institution art="bund" nummer="1"/>
                <betrag>100</betrag>
            </position>
            <position>
                <kategorie type="" subtype=""/>
                <institution art="gemeinede" nummer="20"/>
                <betrag>200</betrag>
            </position>
        </faktura>
    </inkassoFall>
    <inkassoFall id="ik2" forderungjahr="2016" forderungsart="BST_NP" zpvnr="1">
        <faktura id="fk21" valuta="2016-01-01">
            <position>
                <kategorie></kategorie>
                <institution></institution>
                <betrag>300</betrag>
            </position>
        </faktura>
        <faktura  id="fk22" valuta="2017-12-01">
        <position>
            <kategorie type="BUND" subtype=""/>
            <institution art="BUND"/>
            <betrag>1000</betrag>
        </position>
        </faktura>
    </inkassoFall>
    <when>
        <esr art="1" faktura="fk11"/>
        <betrag>900</betrag>
    </when>
    <then></then>
</testcase>

=== mbgt/testcase/src/test/resources/testcase/esrDemo.xml
<?xml version="1.0" encoding="UTF-8"?>

<testcase xmlns="testcase"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation='testcase ../xsd/testcase.xsd'>
    <inkassoFall id="Ik_1" zpvnr="1" forderungsart="BST_NP" forderungsjahr="2016">
        <faktura id="Fk_1" valuta="2015-04-01" belegart="provisorische_abrechnung">
            <position>
                <kategorie type="einkommenssteuer"/>
                <institution art="gemeinde" nummer="1234"/>
                <betrag>300</betrag>
            </position>
            <position>
                <kategorie type="vermoegenssteuer"/>
                <institution art="gemeinde"/>
                <betrag>100</betrag>
            </position>
        </faktura>
    </inkassoFall>
    <when>
        <esr art="1" betrag="600"/>
    </when>
    <then>
        <kontoauszug valuta="2016-05-01" belegart="zahlung">
            <position>
                <kategorie type="einkommenssteuer"/>
                <institution art="gemeinde" nummer="456"/>
                <betrag>450</betrag>
            </position>
            <position>
                <kategorie type="vermoegenssteuer"/>
                <institution art="gemeinde"/>
                <betrag>150</betrag>
            </position>
        </kontoauszug>
    </then>
</testcase>

=== mbgt/testcase/src/test/resources/esrzahlung.xml
<?xml version="1.0" encoding="UTF-8"?>

<testcase xmlns="testcase"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation='testcase ./xsd/testCase.xsd'>
    <inkassoFall id="ik1" forderungjahr="2015" forderungsart="BST_NP" zpvnr="1">
        <faktura id="fk11" valuta="2015">
            <position>
                <kategorie type="" subtype=""/>
                <institution art="bund" nummer="1"/>
                <betrag>100</betrag>
            </position>
            <position>
                <kategorie type="" subtype=""/>
                <institution art="gemeinede" nummer="20"/>
                <betrag>200</betrag>
            </position>
        </faktura>
    </inkassoFall>
    <inkassoFall id="ik2" forderungjahr="2016" forderungsart="BST_NP" zpvnr="1">
        <faktura id="fk21" valuta="1.10.2016">
            <position>
                <kategorie></kategorie>
                <institution></institution>
                <betrag>300</betrag>
            </position>
        </faktura>
    </inkassoFall>
    <when>
        <esr art="1" faktura="fk1" />
    </when>
    <then></then>
</testcase>
